=== ollprogram/ExtensionRetriever/resources/filesTypes.dtd
<!ELEMENT types (type)*>
<!ELEMENT type (name,extension,hex,offset)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT extension (#PCDATA)>
<!ELEMENT hex (#PCDATA)>
<!ELEMENT offset (#PCDATA)>

=== ollprogram/ExtensionRetriever/resources/filesTypes.xml
<?xml version="1.0"?>
<!DOCTYPE types SYSTEM "filesTypes.dtd">
<types>
   <type>
       <name>RedHat Package Manager (RPM) package</name>
       <extension>rpm</extension>
       <hex>ed ab ee db</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Amazon Kindle Update Package</name>
       <extension>bin</extension>
       <hex>53 50 30 31</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>WindowsProgram Information File</name>
       <extension>PIF</extension>
       <hex>00 nn</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>MacStuffit Self-Extracting Archive</name>
       <extension>SEA</extension>
       <hex>00 nn</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>IRISOCR data file</name>
       <extension>YTR</extension>
       <hex>00 nn</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>IBM Storyboard bitmap file</name>
       <extension>PIC</extension>
       <hex>00 nn</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>PalmPilot Database/Document File</name>
       <extension>PDB</extension>
       <hex>00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00</hex>
       <offset>11</offset>
    </type>
   <type>
       <name>Palm Desktop Calendar Archive</name>
       <extension>DBA</extension>
       <hex>BE BA FE CA</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Palm Desktop To Do Archive</name>
       <extension>DBA</extension>
       <hex>00 01 42 44</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Palm Desktop Calendar Archive</name>
       <extension>TDA</extension>
       <hex>00 01 44 54</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Palm Desktop Data File (Access format)</name>
       <extension></extension>
       <hex>00 01 00 00</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Computer icon encoded inICO file format</name>
       <extension>ico</extension>
       <hex>00 00 01 00</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>3rd Generation Partnership Project3GPP</name>
       <extension>3gp</extension>
       <hex>66 74 79 70 33 67</hex>
       <offset>4</offset>
    </type>
   <type>
       <name>3GPP2 multimedia files</name>
       <extension>3g2</extension>
       <hex>66 74 79 70 33 67</hex>
       <offset>4</offset>
    </type>
   <type>
       <name>compressed file (often tar zip)</name>
       <extension>z</extension>
       <hex>1F 9D</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>usingLempel-Ziv-Welch algorithm</name>
       <extension>tar.z</extension>
       <hex>1F 9D</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Compressed file (often tar zip)</name>
       <extension>z</extension>
       <hex>1F A0</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>usingLZH algorithm</name>
       <extension>tar.z</extension>
       <hex>1F A0</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>File ortape containing abackup done withAmiBack on an Amiga. </name>
       <extension>bac</extension>
       <hex>42 41 43 4B 4D 49 4B 45 44 49 53 4B</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Compressed file usingBzip2 algorithm</name>
       <extension>bz2</extension>
       <hex>42 5A 68</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Image file encoded in theGraphics Interchange Format (GIF)</name>
       <extension>gif</extension>
       <hex>47 49 46 38</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Tagged Image File Format (little endian format)</name>
       <extension>tif</extension>
       <hex>49 49 2A 00</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Tagged Image File Format (little endian format)</name>
       <extension>tiff</extension>
       <hex>49 49 2A 00</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Tagged Image File Format (big endian format)</name>
       <extension>tif</extension>
       <hex>4D 4D 00 2A</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Tagged Image File Format (big endian format)</name>
       <extension>tiff</extension>
       <hex>4D 4D 00 2A</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>"Canons RAW format is based on the TIFF file format"</name>
       <extension>cr2</extension>
       <hex>49 49 2A 00 10 00 00 00 43 52</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Canon RAW Format Version 2</name>
       <extension>cr2</extension>
       <hex>49 49 2A 00 10 00 00 00 43 52</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>KodakCineon image</name>
       <extension>cin</extension>
       <hex>80 2A 5F D7</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Compressed file usingRob Northen Compression (version 1 and 2) algorithm</name>
       <extension></extension>
       <hex>52 4E 43 01 52 4E 43 02</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>SMPTEDPX image (big endian format)</name>
       <extension>dpx</extension>
       <hex>53 44 50 58</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>SMPTEDPX image (little endian format)</name>
       <extension>dpx</extension>
       <hex>58 50 44 53</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>OpenEXR image</name>
       <extension>exr</extension>
       <hex>76 2F 31 01</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>Better Portable Graphics format</name>
       <extension>bpg</extension>
       <hex>42 50 47 FB</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>JPEG raw or in theJFIF orExif file format</name>
       <extension>jpg</extension>
       <hex>FF D8 FF DB</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>JPEG raw or in theJFIF orExif file format</name>
       <extension>jpeg</extension>
       <hex>FF D8 FF DB</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>JPEG raw or in theJFIF orExif file format</name>
       <extension>jpg</extension>
       <hex>FF D8 FF E0 nn nn 4A 46 49 46 00 01</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>JPEG raw or in theJFIF orExif file format</name>
       <extension>jpeg</extension>
       <hex>FF D8 FF E0 nn nn 4A 46 49 46 00 01</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>JPEG raw or in theJFIF orExif file format</name>
       <extension>jpg</extension>
       <hex>FF D8 FF E1 nn nn 45 78 69 66 00 00</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>JPEG raw or in theJFIF orExif file format</name>
       <extension>jpeg</extension>
       <hex>FF D8 FF E1 nn nn 45 78 69 66 00 00</hex>
       <offset>0</offset>
    </type>
   <type>
       <name>IFFInterleaved Bitmap Image</name>
       <extension>ilbm</extension>
       <hex>46 4F 52 4D nn nn nn nn 49 4C 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFInterleaved Bitmap Image</name>
       <extension>lbm</extension>
       <hex>46 4F 52 4D nn nn nn nn 49 4C 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFInterleaved Bitmap Image</name>
       <extension>ibm</extension>
       <hex>46 4F 52 4D nn nn nn nn 49 4C 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFInterleaved Bitmap Image</name>
       <extension>iff</extension>
       <hex>46 4F 52 4D nn nn nn nn 49 4C 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFF8-Bit Sampled Voice</name>
       <extension>8svx</extension>
       <hex>46 4F 52 4D nn nn nn nn 38 53 56 58</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFF8-Bit Sampled Voice</name>
       <extension>8sv</extension>
       <hex>46 4F 52 4D nn nn nn nn 38 53 56 58</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFF8-Bit Sampled Voice</name>
       <extension>svx</extension>
       <hex>46 4F 52 4D nn nn nn nn 38 53 56 58</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFF8-Bit Sampled Voice</name>
       <extension>snd</extension>
       <hex>46 4F 52 4D nn nn nn nn 38 53 56 58</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFF8-Bit Sampled Voice</name>
       <extension>iff</extension>
       <hex>46 4F 52 4D nn nn nn nn 38 53 56 58</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>Amiga Contiguous Bitmap</name>
       <extension>acbm</extension>
       <hex>46 4F 52 4D nn nn nn nn 41 43 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>Amiga Contiguous Bitmap</name>
       <extension>iff</extension>
       <hex>46 4F 52 4D nn nn nn nn 41 43 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFAnimated Bitmap</name>
       <extension>anbm</extension>
       <hex>46 4F 52 4D nn nn nn nn 41 4E 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFAnimated Bitmap</name>
       <extension>iff</extension>
       <hex>46 4F 52 4D nn nn nn nn 41 4E 42 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFCEL Animation</name>
       <extension>anim</extension>
       <hex>46 4F 52 4D nn nn nn nn 41 4E 49 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFCEL Animation</name>
       <extension>iff</extension>
       <hex>46 4F 52 4D nn nn nn nn 41 4E 49 4D</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFFacsimile Image</name>
       <extension>faxx</extension>
       <hex>46 4F 52 4D nn nn nn nn 46 41 58 58</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFFacsimile Image</name>
       <extension>faxx</extension>
       <hex>46 4F 52 4D nn nn nn nn 46 41 58 58</hex>
       <offset>any</offset>
    </type>
   <type>
       <name>IFFFacsimile Image</name>
